[project]

name = "wtftw"
version = "0.3.0"
authors = ["Simon Wollwage"]

[dependencies]
bitflags = "0.1"
rustc-serialize = "*"
getopts = "*"
log = "*"
num = "*"
libc = "*"
dylib = "*"

[dependencies.wtftw_core]
path = "core"

[dependencies.wtftw_xlib]
path = "xlib"

[lib]
name = "wtftw"
path = "core/src/wtftw.rs"

[[bin]]
name = "wtftw"
path = "src/wtftw.rs"
