[project]

name = "wtftw"
version = "0.3.1"
authors = ["Simon Wollwage"]

[dependencies]
bitflags = "0.1"
rustc-serialize = "*"
getopts = "*"
log = "*"
num = "*"
libc = "*"
dylib = "*"
zombie = "*"

[dependencies.wtftw_core]
path = "core"

[dependencies.wtftw_xlib]
path = "xlib"

[profile.release]
codegen-units = 8
lto = false

[profile.debug]
codegen-units = 8
lto = false

[lib]
name = "wtftw"
path = "core/src/wtftw.rs"

[[bin]]
name = "wtftw"
path = "src/wtftw.rs"
