[project]

name = "wtftw"
version = "0.3.1"
authors = ["Simon Wollwage"]

[dependencies]
bitflags = "0.1.1"
rustc-serialize = "0.3.15"
getopts = "0.2.11"
log = "0.3.1"
num = "0.1.25"
libc = "0.1.8"
dylib = "0.0.1"
zombie = "0.0.1"

[dependencies.wtftw_core]
path = "core"

[dependencies.wtftw_xlib]
path = "xlib"

[lib]
name = "wtftw"
path = "core/src/wtftw.rs"

[[bin]]
name = "wtftw"
path = "src/wtftw.rs"
