[project]

name = "wtftw_xlib"
version = "0.4.0"
authors = ["Simon Wollwage"]

[dependencies]
log = "*"
libc = "*"
x11 = "*"

[dependencies.wtftw_core]
path = "../core"

[lib]
name = "wtftw_xlib"
path = "src/xlib_window_system.rs"
crate-type = ["rlib"]
